# Generated by Django 4.2 on 2023-04-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="status",
            new_name="still_exist",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="organization",
            name="address",
            field=models.CharField(default="IL, Chicago", max_length=255),
        ),
    ]
