# Generated by Django 4.2 on 2023-04-20 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
            },
        ),
        migrations.CreateModel(
            name="TechnologyStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technology_stack",
                    models.CharField(
                        choices=[
                            ("PYTHON", "Python"),
                            ("JAVA", "Java"),
                            ("JAVASCRIPT", "JavaScript"),
                            ("C_SHARP", "C#"),
                            ("PHP", "PHP"),
                            ("RUBY", "Ruby"),
                            ("SWIFT", "Swift"),
                            ("KOTLIN", "Kotlin"),
                            ("GO", "Go"),
                            ("TYPESCRIPT", "TypeScript"),
                            ("C_PLUS_PLUS", "C++"),
                            ("C", "C"),
                            ("OBJECTIVE_C", "Objective-C"),
                            ("SQL", "SQL"),
                            ("HTML_CSS", "HTML/CSS"),
                            ("PERL", "Perl"),
                            ("SHELL", "Shell"),
                            ("R", "R"),
                            ("MATLAB", "MATLAB"),
                            ("SCALA", "Scala"),
                            ("GROOVY", "Groovy"),
                            ("VB_NET", "VB.NET"),
                            ("VISUAL_BASIC", "Visual Basic"),
                            ("SWIFTUI", "SwiftUI"),
                            ("REACT", "React"),
                            ("ANGULAR", "Angular"),
                            ("VUE_JS", "Vue.js"),
                            ("NODE_JS", "Node.js"),
                            ("DJANGO", "Django"),
                            ("RAILS", "Ruby on Rails"),
                            ("SPRING", "Spring"),
                            ("LARAVEL", "Laravel"),
                            ("ASP_NET", "ASP.NET"),
                            ("EXPRESS_JS", "Express.js"),
                            ("FLASK", "Flask"),
                            ("REACT_NATIVE", "React Native"),
                            ("XAMARIN", "Xamarin"),
                            ("UNITY", "Unity"),
                            ("FLUTTER", "Flutter"),
                            ("ANDROID", "Android"),
                            ("IOS", "iOS"),
                            ("AWS", "Amazon Web Services (AWS)"),
                            ("AZURE", "Microsoft Azure"),
                            ("GOOGLE_CLOUD", "Google Cloud Platform (GCP)"),
                            ("DOCKER", "Docker"),
                            ("KUBERNETES", "Kubernetes"),
                            ("TERRAFORM", "Terraform"),
                            ("ELASTICSEARCH", "Elasticsearch"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "technology stack",
                "verbose_name_plural": "technology stacks",
            },
        ),
        migrations.CreateModel(
            name="TechnologyStackGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tech_stack_group",
                    models.CharField(
                        choices=[
                            ("MEN", "MEAN/MERN"),
                            ("LAMP", "LAMP"),
                            ("FULL_STACK", "Full-Stack"),
                            ("BACKEND", "Backend"),
                            ("FRONTEND", "Frontend"),
                            ("DATA_SCIENCE", "Data Science"),
                            ("MOBILE", "Mobile Development"),
                            ("GAME_DEV", "Game Development"),
                            ("DEV_OPS", "DevOps"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "technology stack group",
                "verbose_name_plural": "technology stack groups",
            },
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("is_owner", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recruiter",
                "verbose_name_plural": "recruiters",
            },
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("resume", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                (
                    "tech_stack_group",
                    models.ManyToManyField(
                        related_name="stack_group", to="users.technologystackgroup"
                    ),
                ),
                (
                    "technology_stack",
                    models.ManyToManyField(
                        related_name="tech_stack", to="users.technologystack"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
