version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SETTINGS: ${SETTINGS}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    volumes:
      - .:/app
      - logs:/app/logs
    depends_on:
      - db
    networks:
      - django-network
    container_name: django

  db:
    image: postgres:12.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - django-network
    container_name: apexive_database
    restart: unless-stopped

networks:
  django-network:

volumes:
  db:
  logs:
