version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
      - logs:/app/logs
    depends_on:
      - db
    networks:
      - django-network
    container_name: django

  db:
    image: postgres:12.2
    env_file:
      - .env
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - django-network
    container_name: apexive_database
    restart: unless-stopped

networks:
  django-network:

volumes:
  db:
  logs:
