# Generated by Django 4.2 on 2023-04-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agency_app", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="applicants",
            field=models.ManyToManyField(
                related_name="jobs_applied_to", to="users.applicant"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="recruiter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="users.recruiter",
            ),
        ),
    ]
