# Generated by Django 4.2 on 2023-04-20 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_organization_technologystack_technologystackgroup_and_more"),
        ("agency_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="applicants",
            field=models.ManyToManyField(
                null=True, related_name="jobs_applied_to", to="users.applicant"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="recruiter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="users.recruiter",
            ),
        ),
    ]
