# Generated by Django 4.2 on 2023-04-16 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ("-date_posted",)},
        ),
    ]
