from enum import Enum


class TechStack(Enum):
    PYTHON = "Python"
    JAVA = "Java"
    JAVASCRIPT = "JavaScript"
    C_SHARP = "C#"
    PHP = "PHP"
    RUBY = "Ruby"
    SWIFT = "Swift"
    KOTLIN = "Kotlin"
    GO = "Go"
    TYPESCRIPT = "TypeScript"
    C_PLUS_PLUS = "C++"
    C = "C"
    OBJECTIVE_C = "Objective-C"
    SQL = "SQL"
    HTML_CSS = "HTML/CSS"
    PERL = "Perl"
    SHELL = "Shell"
    R = "R"
    MATLAB = "MATLAB"
    SCALA = "Scala"
    GROOVY = "Groovy"
    VB_NET = "VB.NET"
    VISUAL_BASIC = "Visual Basic"
    SWIFTUI = "SwiftUI"
    REACT = "React"
    ANGULAR = "Angular"
    VUE_JS = "Vue.js"
    NODE_JS = "Node.js"
    DJANGO = "Django"
    RAILS = "Ruby on Rails"
    SPRING = "Spring"
    LARAVEL = "Laravel"
    ASP_NET = "ASP.NET"
    EXPRESS_JS = "Express.js"
    FLASK = "Flask"
    REACT_NATIVE = "React Native"
    XAMARIN = "Xamarin"
    UNITY = "Unity"
    FLUTTER = "Flutter"
    ANDROID = "Android"
    IOS = "iOS"
    AWS = "Amazon Web Services (AWS)"
    AZURE = "Microsoft Azure"
    GOOGLE_CLOUD = "Google Cloud Platform (GCP)"
    DOCKER = "Docker"
    KUBERNETES = "Kubernetes"
    TERRAFORM = "Terraform"
    ELASTICSEARCH = "Elasticsearch"
    OTHER = "Other"


class TechStackGroup(Enum):
    MEN = "MEAN/MERN"
    LAMP = "LAMP"
    FULL_STACK = "Full-Stack"
    BACKEND = "Backend"
    FRONTEND = "Frontend"
    DATA_SCIENCE = "Data Science"
    MOBILE = "Mobile Development"
    GAME_DEV = "Game Development"
    DEV_OPS = "DevOps"
    OTHER = "Other"
